### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by tk1363704** [tsinghua-fib-lab/pycityagent#1]
Thank you for sharing your project! We are very interested in and enthusiastic about it. However, we encountered the following issues while attempting to run the project:

1. In config_template.yaml, we noticed a parameter requiring configuration: mongo_uri: <MONGO_URI>. Could you please clarify what data we need to manage in the MongoDB database? Additionally, how should we configure the MongoDB database to enable the project to connect to it properly?

2. Within the examples folder, we found several subfolders. Could you provide guidance on how to get started with running the project? The README file does not seem to specify a clear starting point.

We appreciate your help and look forward to your response. Thank you!

**Comment by tk1363704** [comment]
Hi all,

Do we have any comments on this thread? Cheers!

**Comment by PinkGranite** [comment]
Hi, 
Thank you so much for your interest in our project and for taking the time to explore it! We truly appreciate your enthusiasm.

Regarding your questions:
	1.	Project Status – At this stage, the project is under rapid development and is not yet ready for direct usage. Some configurations, including mongo_uri, are placeholders as we continue building the necessary components.
	2.	Future Plans – We plan to release a comprehensive suite of tools and components in the near future. This will include maps, traffic simulators, economic simulators, and social agent implementations, which will streamline the process of running and experimenting with the project.
	3.	Next Steps – We recommend keeping an eye on our updates. We will notify you as soon as the project reaches a stable, usable state and provide clear instructions for setup and execution.

Thank you again for your support and understanding. 

Best regards

**Comment by PinkGranite** [comment]
I will close this issue at this stage. Thank you.
